apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules
  labels:
    release: prometheus
spec:
  groups:
  - name: SLOs-http_server_requests_seconds_count
    rules:
    - alert: ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=planetarium-clusterip (current value: {{ $value }})'
      expr: |
        sum(http_server_requests_seconds_count:burnrate5m{job="planetarium-clusterip"}) > (14.40 * (1-0.99900))
        and
        sum(http_server_requests_seconds_count:burnrate1h{job="planetarium-clusterip"}) > (14.40 * (1-0.99900))
      for: 2m
      labels:
        job: planetarium-clusterip
        severity: critical
    - alert: ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=planetarium-clusterip (current value: {{ $value }})'
      expr: |
        sum(http_server_requests_seconds_count:burnrate30m{job="planetarium-clusterip"}) > (6.00 * (1-0.99900))
        and
        sum(http_server_requests_seconds_count:burnrate6h{job="planetarium-clusterip"}) > (6.00 * (1-0.99900))
      for: 15m
      labels:
        job: planetarium-clusterip
        severity: critical
    - alert: ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=planetarium-clusterip (current value: {{ $value }})'
      expr: |
        sum(http_server_requests_seconds_count:burnrate2h{job="planetarium-clusterip"}) > (3.00 * (1-0.99900))
        and
        sum(http_server_requests_seconds_count:burnrate1d{job="planetarium-clusterip"}) > (3.00 * (1-0.99900))
      for: 30m
      labels:
        job: planetarium-clusterip
        severity: warning
    - alert: ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=planetarium-clusterip (current value: {{ $value }})'
      expr: |
        sum(http_server_requests_seconds_count:burnrate6h{job="planetarium-clusterip"}) > (1.00 * (1-0.99900))
        and
        sum(http_server_requests_seconds_count:burnrate3d{job="planetarium-clusterip"}) > (1.00 * (1-0.99900))
      for: 2h
      labels:
        job: planetarium-clusterip
        severity: warning
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[1d]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1d]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate1d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[1h]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1h]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate1h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[2h]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[2h]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate2h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[30m]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[30m]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate30m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[3d]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[3d]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate3d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[5m]))
      labels:
        job: planetarium-clusterip
      record: http_server_requests_seconds_count:burnrate5m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip",status=~"5.."}[6h]))
        /
        sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[6h]))
      labels:
        job: planetarium-clusterip
        record: http_server_requests_seconds:burnrate6h
  - name: planetarium #alert name
    rules:

    - alert: AppDown
      expr: up == 0 # expression
      for: 5m #pending period of 5 minute  basic wait 5 min before alert you. if you fix it before 5 min it wont alert you
      labels:
        severity: warn
      annotations:
        summary: "App planetarium is down"
        description: "Prometheus has detected the application is not running for 5 minutes"

    - alert: AppDownTooLong
      expr: up == 0
      for: 10m #pending period of 5 minute  basic wait 5 min before alert you. if you fix it before 5 min it wont alert you
      labels:
        severity: critical
      annotations:
        summary: "planetarium not running"
        description: "Prometheus has detected the application is not running for 10 minutes"

    - alert: APIHighLatency:5min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[5m])) > 0.2
      #for:
      labels:
        severity: warn
      annotations:
        summary: "5 min latency too high"
        description: "planetarium application is taking too long to handle requests in a 5 minute range"

    - alert: APIHighLatency:15min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[15m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[15m])) > 0.2
      #for:
      labels:
        severity: warn
      annotations:
        summary: "15 min latency too high"
        description: "planetarium application is taking too long to handle requests in a 15 minute range"

    - alert: APIHighLatency:30min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[30m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[30m])) > 0.2
      #for:
      labels:
        severity: warn
      annotations:
        summary: "30 min latency too high"
        description: "planetarium application is taking too long to handle requests in a 30 minute range"

    - alert: APIHighLatency:1hour
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[1h])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1h])) > 0.2
      #for:
      labels:
        severity: warn
      annotations:
        summary: "1 hour latency too high"
        description: "planetarium application is taking too long to handle requests in a 1 hour range" 